#include<stdio.h>
int main()
{
	int row,column;
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(row==0&&column==2||row==1&&column==1||row==1&&column==3||row==2&&column==1||row==2&&column==2||row==2&&column==3||row==3&&column==1||row==3&&column==3||row==4&&column==1||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||column==4&&row==1||column==4&&row==2||column==4&&row==3||row==0&&column==2||row==0&&column==3||row==2&&column==2||row==2&&column==3||row==4&&column==2||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==0&&column!=0||row==4&&column!=0)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==0&&column==2||row==4&&column==2||column==4&&row==1||column==4&&row==2||column==4&&row==3||row==0&&column==3||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==0&&column==2||row==0&&column==3||row==2&&column==2||row==2&&column==3||row==2&&column==4||row==4&&column==2||row==4&&column==3||row==0&&column==4||row==4&&column==4)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==0&&column!=0||row==2&&column!=0)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==0||row==0||row==2&&column!=1||row==2&&column==2||row==3&&column==2||row==4&&column==2||row==2&&column==4||row==3&&column==4||row==4&&column==4||row==4&&column==1)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||column==4||row==2&&column==2||row==2&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==2||row==0||row==4)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(row==0||column==2&&row!=4||row==4&&column==0||row==4&&column==1)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==0&&column==3||row==1&&column==2||row==3&&column==2||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==4&&column==1||row==4&&column==2||row==4&&column==3||row==4&&column==4)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==0||column==4||row==1&&column==1||row==1&&column==3||row==2&&column==2)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==0||column==4||row==1&&column==1||row==2&&column==2||row==3&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||column==4||row==0&&column==2||row==4&&column==2||row==0&&column==3||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==0&&column!=0||row==2&&column!=0||row==1&&column==4)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(row==0||row==3||row==1&&column==0||row==1&&column==4||row==2&&column==0||row==2&&column==4||column==2||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	
	
	
	
	
	
	
	
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||row==0&&column==2||row==0&&column==3||row==1&&column==3||row==2&&column==2||row==2&&column==3||row==3&&column==2||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(row==0&&column==2||row==0&&column==3||row==1&&column==1||row==2&&column==2||row==3&&column==3||row==4&&column==1||row==4&&column==2)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(row==0||column==2)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==1||column==4||row==4&&column==2||row==4&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==0&&row==0||column==0&&row==1||column==0&&row==2||column==4&&row==0||column==4&&row==1||column==4&&row==2||row==3&&column==1||row==3&&column==3||row==4&&column==2)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==0||column==4||row==2&&column==2||row==3&&column==1||row==3&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(row==0&&column==0||row==0&&column==4||row==1&&column==1||row==1&&column==3||row==2&&column==2||row==3&&column==1||row==3&&column==3||row==4&&column==0||row==4&&column==4)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(column==2&&row==2||column==2&&row==3||column==2&&row==4||row==0&&column==0||row==0&&column==4||row==1&&column==1||row==1&&column==3)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
	printf("\n");
	for(row=0;row<5;row++)
	{
		for(column=0;column<5;column++)
		{
			if(row==0||row==4||row==1&&column==3||row==2&&column==2||row==3&&column==1)
			{
				printf("*");
			}
			else
			{
				printf(" ");
			}
		}
		printf("\n");
	}
}

